// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// sbh20 //
// ----- //

#define sbh20_wrap_target 0
#define sbh20_wrap 27

#define sbh20_offset_set_x 22u

static const uint16_t sbh20_program_instructions[] = {
    //     .wrap_target
    0x30a2,  //  0: wait   1 pin, 2        side 0
    0x2022,  //  1: wait   0 pin, 2
    0xe04f,  //  2: set    y, 15
    0x2021,  //  3: wait   0 pin, 1
    0x20a1,  //  4: wait   1 pin, 1
    0x4001,  //  5: in     pins, 1
    0x0083,  //  6: jmp    y--, 3
    0xa046,  //  7: mov    y, isr
    0x8000,  //  8: push   noblock
    0xc000,  //  9: irq    nowait 0
    0x00a0,  // 10: jmp    x != y, 0
    0x20a2,  // 11: wait   1 pin, 2
    0xe05f,  // 12: set    y, 31
    0xa742,  // 13: nop                           [7]
    0xa542,  // 14: nop                           [5]
    0x008d,  // 15: jmp    y--, 13
    0xf881,  // 16: set    pindirs, 1      side 1
    0xe05f,  // 17: set    y, 31
    0xa642,  // 18: nop                           [6]
    0x0092,  // 19: jmp    y--, 18
    0xf080,  // 20: set    pindirs, 0      side 0
    0x0000,  // 21: jmp    0
    0xe080,  // 22: set    pindirs, 0
    0x80a0,  // 23: pull   block
    0xa027,  // 24: mov    x, osr
    0xa0c3,  // 25: mov    isr, null
    0x8000,  // 26: push   noblock
    0xc000,  // 27: irq    nowait 0
             //     .wrap
};

// without debug
// static const uint16_t sbh20_program_instructions[] = {
//     //     .wrap_target
//     0x20a2,  //  0: wait   1 pin, 2
//     0x2022,  //  1: wait   0 pin, 2
//     0xe04f,  //  2: set    y, 15
//     0x2021,  //  3: wait   0 pin, 1
//     0x20a1,  //  4: wait   1 pin, 1
//     0x4001,  //  5: in     pins, 1
//     0x0083,  //  6: jmp    y--, 3
//     0xa046,  //  7: mov    y, isr
//     0x8000,  //  8: push   noblock
//     0xc000,  //  9: irq    nowait 0
//     0x00a0,  // 10: jmp    x != y, 0
//     0x20a2,  // 11: wait   1 pin, 2
//     0xe081,  // 12: set    pindirs, 1
//     0x2022,  // 13: wait   0 pin, 2
//     0xe080,  // 14: set    pindirs, 0
//     0x0000,  // 15: jmp    0
//     0xe080,  // 16: set    pindirs, 0
//     0x80a0,  // 17: pull   block
//     0xa027,  // 18: mov    x, osr
//     0xa0c3,  // 19: mov    isr, null
//     0x8000,  // 20: push   noblock
//     0xc000,  // 21: irq    nowait 0
//              //     .wrap
// };

#if !PICO_NO_HARDWARE
static const struct pio_program sbh20_program = {
    .instructions = sbh20_program_instructions,
    .length = 28,
    .origin = -1,
};

static inline pio_sm_config sbh20_program_get_default_config(uint offset) {
  pio_sm_config c = pio_get_default_sm_config();
  sm_config_set_wrap(&c, offset + sbh20_wrap_target, offset + sbh20_wrap);
  sm_config_set_sideset(&c, 2, true, false);
  return c;
}
#endif